name: NewYearBlessing
version: 1.3.2
main: moink.newyearblessing.NewYearBlessing
api-version: 1.18
commands:
  newyearblessing:
    aliases:
      - "nyb"
    description: "主指令"
permissions:
  nyb.commands.reload:
    description: "重载插件的权限"
    default: op