name: NewyearBlessing
version: 1.0-SNAPSHOT
main: newyearblessing.newyearblessing.NewyearBlessing
api-version: 1.15
commands:
  nyb:
    description: 主指令
permissions:
  customhub.command.reload:
    description: 重载插件的权限
    default: op