name: NewyearBlessing
version: 1.3.1
main: newyearblessing.newyearblessing.NewyearBlessing
api-version: 1.15
commands:
  nyb:
    description: 主指令
permissions:
  newyearblessing.command.reload:
    description: 重载插件的权限
    default: op