message-reload: ' 插件重载成功'
message-upload: ' 祝福上传成功，你获得了一个钻石！'
message-di: ' 第'
message-is: '个人的祝福是：'
message-error: ' 语法错误'
message-list: ' 祝福列表'
message-already: ' 你已经写过祝福了'
message-no: '你没有权限这么做'
#以上是一些语言文件
reward: 'give %player_name% diamond'
#玩家许愿成功后执行的指令，支持papi
Blessing: